[package]
name = "navarro_blog_api"
version = "0.1.0"
edition = "2021"
description = "The Blog API is a web development application focused on providing functionality to manage and interact with the content of a personal blog through programmatic calls."
license = "MIT"
readme = "README.md"
authors = [
  "Victor Navarro <victor.jose.lopes.navarro@gmail.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
utoipa = { version = "4.2.3", features = ["actix_extras"]}
utoipa-swagger-ui = { version = "7.1.0", features = ["actix-web"] }