name: Navarro Blog API Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: blogdb
  DB_USER: postgres
  DB_PASSWORD: 220305
  POOL_SIZE: 125

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --test-threads=1
